name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: Newby19

          # List of files to generate.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Newby19
          author_email: Workwithsankalp008@gmail.com
          message: 'Update contribution snake'
          add: 'dist/*'
