name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: Newby19
          outputs: dist/snake.svg

      - name: Upload Snake to Repository
        run: |
          mkdir -p dist
          mv dist/snake.svg ./snake.svg
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update contribution snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
