name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: Newby19  # Replace with your GitHub username
          outputs: "dist/snake.svg"

      - name: Upload Snake to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-contribution
          path: dist/snake.svg
