name: Update README for Newby19

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Newby19's repo README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v1.0.1  # Use a specific version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
